# Generated by Django 5.2.17 on 2026-08-28 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('command', models.CharField(max_length=50)),
                ('stories_fetched', models.PositiveIntegerField(default=0)),
                ('stories_scored', models.PositiveIntegerField(default=0)),
                ('stories_generated', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('feed_url', models.URLField(max_length=500)),
                ('homepage_url', models.URLField(blank=True, max_length=500)),
                ('city', models.CharField(choices=[('san_antonio', 'San Antonio'), ('dallas', 'Dallas'), ('fort_worth', 'Fort Worth'), ('el_paso', 'El Paso'), ('corpus_christi', 'Corpus Christi'), ('statewide', 'Statewide'), ('other', 'Other')], default='statewide', max_length=20)),
                ('is_cowboys', models.BooleanField(default=False, help_text='Hint: this source is Cowboys-focused.')),
                ('is_active', models.BooleanField(default=True)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True)),
                ('published_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('image_file', models.CharField(blank=True, help_text='Path under MEDIA_ROOT.', max_length=500)),
                ('image_width', models.PositiveIntegerField(blank=True, null=True)),
                ('image_height', models.PositiveIntegerField(blank=True, null=True)),
                ('cluster_key', models.CharField(blank=True, db_index=True, max_length=200)),
                ('cluster_size', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('new', 'New'), ('scored', 'Scored'), ('generated', 'Generated'), ('posted', 'Posted'), ('skipped', 'Skipped'), ('hidden', 'Hidden')], db_index=True, default='new', max_length=12)),
                ('importance', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('shareability', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('weather', 'Weather & Severe Storms'), ('wildfires', 'Wildfires'), ('hurricanes', 'Hurricanes'), ('community', 'Community & Human Interest'), ('business', 'Local Business & Economy'), ('cost_of_living', 'Cost of Living'), ('history', 'Texas History / Nostalgia'), ('cowboys', 'Cowboys (Slow News)'), ('football_culture', 'HS & College Football Culture'), ('food', 'Food & BBQ'), ('texas_pride', 'Texas Pride'), ('politics', 'Politics (Hidden)'), ('sports_live', 'Live Sports (Hidden)'), ('other', 'Other')], max_length=20)),
                ('is_political', models.BooleanField(blank=True, null=True)),
                ('is_cowboys', models.BooleanField(blank=True, null=True)),
                ('score_reason', models.TextField(blank=True)),
                ('scored_at', models.DateTimeField(blank=True, null=True)),
                ('post_title', models.CharField(blank=True, max_length=200)),
                ('post_description', models.TextField(blank=True)),
                ('reel_script', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('skipped_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='news.source')),
            ],
            options={
                'verbose_name_plural': 'stories',
                'ordering': ['-published_at'],
            },
        ),
    ]
