# Generated by Django 5.2.17 on 2026-08-29 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_push_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='notified_at',
            field=models.DateTimeField(blank=True, help_text='Push notification sent.', null=True),
        ),
    ]
