# Generated by Django 5.2.17 on 2026-09-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_story_notified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinerun',
            name='stories_ranked',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='stories_triaged',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='analysed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='article_words',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Words of article text sent to Claude. The text itself is never stored.', null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='consequence',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-5: does this change money, safety or plans.', null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='daily_rank',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='dimension_notes',
            field=models.JSONField(blank=True, default=dict, help_text='One justification per dimension, quoting the article.'),
        ),
        migrations.AddField(
            model_name='story',
            name='key_facts',
            field=models.JSONField(blank=True, default=list, help_text='3-5 facts extracted from the article.'),
        ),
        migrations.AddField(
            model_name='story',
            name='novelty',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-5: genuinely new, not a rehash.', null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='performance',
            field=models.CharField(blank=True, choices=[('well', 'Did well'), ('poorly', 'Did poorly')], max_length=10),
        ),
        migrations.AddField(
            model_name='story',
            name='performance_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='proximity',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-5: closeness to the five target cities.', null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='ranked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='read_confidence',
            field=models.CharField(blank=True, choices=[('full', 'Article read'), ('partial', 'Partial read'), ('headline_only', 'Headline only')], max_length=13),
        ),
        migrations.AddField(
            model_name='story',
            name='scale',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-5: how many Texans this affects, and where.', null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='share_trigger',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-5: why a 55-year-old sends it to family.', null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='shelf_life',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-5: still worth posting in 12 hours.', null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='triage_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='story',
            name='triage_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-5 rough interest, from the headline alone.', null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='triaged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('triaged', 'Triaged'), ('scored', 'Scored'), ('generated', 'Generated'), ('posted', 'Posted'), ('skipped', 'Skipped'), ('hidden', 'Hidden')], db_index=True, default='new', max_length=12),
        ),
    ]
