# Generated by Django 5.2.17 on 2026-09-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_scoring_cascade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='importance',
        ),
        migrations.RemoveField(
            model_name='story',
            name='shareability',
        ),
        migrations.AlterField(
            model_name='story',
            name='triage_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-5 rough interest, judged from the headline alone.', null=True),
        ),
    ]
