# Generated by Django 5.2.17 on 2026-09-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_cowboys_live_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='category',
            field=models.CharField(blank=True, choices=[('weather', 'Weather & Severe Storms'), ('wildfires', 'Wildfires'), ('hurricanes', 'Hurricanes'), ('community', 'Community & Human Interest'), ('business', 'Local Business & Economy'), ('cost_of_living', 'Cost of Living'), ('history', 'Texas History / Nostalgia'), ('cowboys', 'Cowboys'), ('football_culture', 'HS & College Football Culture'), ('food', 'Food & BBQ'), ('texas_pride', 'Texas Pride'), ('politics', 'Politics (Hidden)'), ('sports_live', 'Live Sports (Hidden)'), ('other', 'Other')], max_length=20),
        ),
    ]
