# Generated by Django 5.2.17 on 2026-09-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_more_cowboys_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='category',
            field=models.CharField(blank=True, choices=[('game', 'Game & Matchups'), ('roster', 'Roster Moves'), ('injury', 'Injuries'), ('coaching', 'Coaching & Front Office'), ('draft', 'Draft & Prospects'), ('off_field', 'Off the Field'), ('fan', 'Fan Culture'), ('history', 'History & Nostalgia'), ('cowboys', 'Cowboys (general)'), ('politics', 'Politics (Hidden)'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='story',
            name='consequence',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-5: does this change the roster, the season or the next game.', null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='proximity',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-5: how directly this is about the Cowboys.', null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='scale',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-5: how much of the team or season this touches.', null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='share_trigger',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-5: why a Cowboys fan sends it to another fan.', null=True),
        ),
    ]
