# Generated by Django 5.2.17 on 2026-09-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_cowboys_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='emoji',
            field=models.CharField(blank=True, help_text="One emoji matching the story's tone, shown before the description.", max_length=8),
        ),
    ]
